In [1]:
from constrerl.erl_schema import (
    entity_labels,
    relations,
    
)
from constrerl.annotator import Annotator, AnnotationTypes, article_to_sentences
from constrerl.annotation_model import (
    AnnotatedArticle,
    load_collection,
    Entity    
)

In [2]:
dev_articles=load_collection("Dev")
train_articles=load_collection("Train")

In [3]:
train_human ={id:train_article for id, train_article in train_articles.items() if train_article.metadata.annotator != "distant"}
print(f"Train human articles: {len(train_human)}")
print(f"Train distant articles: {len(train_articles)-len(train_human)}")

Train human articles: 1949
Train distant articles: 2972

In [4]:
import datasets

In [5]:
label_list = ["O", "B-NE", "I-NE"]
label2id = {l: i for i, l in enumerate(label_list)}
id2label = {i: l for l, i in label2id.items()}

In [6]:
from transformers import AutoTokenizer, AutoModelForTokenClassification

model_name = "microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract"

tokenizer = AutoTokenizer.from_pretrained(model_name, )

model = AutoModelForTokenClassification.from_pretrained(
    model_name,
    num_labels=len(label_list),
    id2label=id2label,
    label2id=label2id
)

Some weights of BertForTokenClassification were not initialized from the model checkpoint at microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [7]:
def convert_to_token_labels(
    text: str, entities: list[Entity], tokenizer: AutoTokenizer, label2id: dict
):
    encoding = tokenizer(
        text, return_offsets_mapping=True, padding='max_length', max_length=128, truncation=True
    )

    offsets = encoding["offset_mapping"]
    labels = ["O"] * len(offsets)

    for ent in entities:
        for i, (token_start, token_end) in enumerate(offsets):
            if token_start >= ent.end_idx or token_end <= ent.start_idx:
                continue

            if token_start == ent.start_idx:
                labels[i] = "B-NE"
            else:
                labels[i] = "I-NE"
    # convert to ids + mask special tokens
    label_ids = []
    for i, label in enumerate(labels):
        if offsets[i] == (0, 0):  # special tokens like [CLS]
            label_ids.append(-100)
        else:
            label_ids.append(label2id[label])

    encoding["labels"] = label_ids
    return encoding

In [8]:
import tqdm


def gen_dataset(
    articles: dict[int, AnnotatedArticle], tokenizer, label2id
):
    for article in tqdm.tqdm(articles.values()):
        sentences = article_to_sentences(article.metadata, entities=article.entities)
        for sentence in sentences:
            
            text = sentence.text

            encoding = convert_to_token_labels(text, sentence.entities, tokenizer, label2id)
            yield encoding

In [9]:
import pandas as pd
train_df = pd.DataFrame(gen_dataset(train_articles, tokenizer, label2id))
eval_df = pd.DataFrame(gen_dataset(dev_articles, tokenizer, label2id))

100%|██████████| 4921/4921 [00:05<00:00, 886.19it/s]
100%|██████████| 80/80 [00:00<00:00, 717.44it/s]

In [10]:
train_df

,input_ids,token_type_ids,attention_mask,offset_mapping,labels
0,"[2, 7760, 10998, 1682, 2743, 5468, 3028, 8275,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[(0, 0), (0, 3), (4, 14), (15, 17), (18, 23), ...","[-100, 1, 2, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, ..."
1,"[2, 5199, 1682, 1680, 7760, 6512, 4085, 4442, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[(0, 0), (0, 11), (12, 14), (15, 18), (19, 22)...","[-100, 0, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 1, 2, ..."
2,"[2, 6512, 4085, 5345, 1748, 2170, 1955, 2743, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[(0, 0), (0, 9), (10, 19), (20, 28), (29, 33),...","[-100, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 0, 1, ..."
3,"[2, 2564, 663, 5661, 2281, 3186, 2520, 21, 228...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[(0, 0), (0, 8), (9, 10), (10, 12), (13, 18), ...","[-100, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ..."
4,"[2, 5169, 1955, 5864, 3321, 1690, 1680, 10998,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[(0, 0), (0, 12), (13, 20), (21, 28), (29, 44)...","[-100, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ..."
...,...,...,...,...,...
53240,"[2, 1680, 7692, 1685, 31, 50, 33, 5835, 14578,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[(0, 0), (0, 3), (4, 13), (14, 16), (17, 18), ...","[-100, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0, 0, ..."
53241,"[2, 1680, 7692, 1685, 31, 50, 33, 4811, 20396,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[(0, 0), (0, 3), (4, 13), (14, 16), (17, 18), ...","[-100, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, ..."
53242,"[2, 31, 50, 33, 10277, 7423, 31, 18, 50, 33, 7...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[(0, 0), (0, 1), (1, 2), (2, 3), (3, 7), (7, 1...","[-100, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, ..."
53243,"[2, 1680, 2727, 14641, 1012, 3503, 1682, 1680,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[(0, 0), (0, 3), (4, 9), (10, 13), (13, 14), (...","[-100, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, ..."
53244,"[2, 1680, 1890, 2857, 1760, 1680, 13798, 1922,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[(0, 0), (0, 3), (4, 11), (12, 24), (25, 29), ...","[-100, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 2, 0, ..."

In [11]:
train_dataset = datasets.Dataset.from_pandas(train_df)
eval_dataset = datasets.Dataset.from_pandas(eval_df)

In [12]:
train_dataset

Dataset({
    features: ['input_ids', 'token_type_ids', 'attention_mask', 'offset_mapping', 'labels'],
    num_rows: 53245
})

In [13]:
len(train_dataset[3]["attention_mask"])

128

In [14]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./finetuned/ned",
    learning_rate=3e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=32,
    gradient_accumulation_steps=2,
    num_train_epochs=5,    
    warmup_ratio=0.1,                   # critical for stability with higher LR
    weight_decay=0.01,
    # evaluation_strategy="epoch",
    save_strategy="epoch",
    logging_steps=200,
    eval_steps=500,
    fp16=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    tokenizer=tokenizer,
)

trainer.train()

/tmp/ipykernel_3920732/1886032811.py:19: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

TrainOutput(global_step=16640, training_loss=0.10356241981857098, metrics={'train_runtime': 629.2169, 'train_samples_per_second': 423.105, 'train_steps_per_second': 26.446, 'total_flos': 1.73910894958656e+16, 'train_loss': 0.10356241981857098, 'epoch': 5.0})

In [15]:
# annotate dev articles with the trained model

import torch
from constrerl.sentences import annotated_sentences_to_article


def detect_entities(
    article: AnnotatedArticle,
    model: AutoModelForTokenClassification,
    tokenizer: AutoTokenizer,
):
    sentences = article_to_sentences(
        article.metadata,
    )
    entities: list[Entity] = []
    for sentence in sentences:
        text = sentence.text
        tokens = tokenizer(
            text,
            return_offsets_mapping=True,
            padding="max_length",
            max_length=128,
            truncation=True,
        )
        input_ids = (
            torch.tensor(tokens["input_ids"]).unsqueeze(0).to(model.device)
        )  # batch size 1
        attention_mask = (
            torch.tensor(tokens["attention_mask"]).unsqueeze(0).to(model.device)
        )
        predictions = model(input_ids=input_ids, attention_mask=attention_mask)
        predicted_labels = predictions.logits.argmax(dim=-1).squeeze().tolist()
        print(predicted_labels)
        offsets = tokens["offset_mapping"]
        entities_sentence: list[Entity] = []
        current_entity: Entity = None
        last_end_idx = 0
        is_running = False
        def finish_current_entity():
            nonlocal current_entity, last_end_idx, is_running
            if current_entity is not None and is_running:
                current_entity.end_idx = last_end_idx
                current_entity.text_span = text[
                    current_entity.start_idx : current_entity.end_idx
                ]
                entities_sentence.append(current_entity)
                current_entity = None
        for label_id, (start, end) in zip(predicted_labels, offsets):
            if label_id == label2id["O"]:
                finish_current_entity()
                is_running = False
                continue
            if label_id == label2id["B-NE"]:
                finish_current_entity()
                current_entity = Entity(
                    start_idx=start,
                    end_idx=end,
                    label="NE",
                    location="title" if sentence.title else "abstract",
                    text_span=text[start:end],
                )
                is_running = True
                last_end_idx = end
            if label_id == label2id["I-NE"] or label_id == label2id["B-NE"]:
                last_end_idx = end
        finish_current_entity()
        filtered_ents = []
        for ent in entities_sentence:
            if ent.text_span.strip() != "":
                ent.end_idx = ent.end_idx - 1
                filtered_ents.append(ent)
            sentence.entities = filtered_ents
    return annotated_sentences_to_article(sentences, article.metadata)


ned_dev_articles = {}
annotated_articles = {}
for id, article in dev_articles.items():
    article_cp = AnnotatedArticle(**article.__dict__)
    for ent in article_cp.entities:
        ent.label = "NE"
    annotated_article = detect_entities(article_cp, model, tokenizer)
    ned_dev_articles[id] = article_cp
    annotated_articles[id] = annotated_article
    print(f"Article {article.metadata.title} detected entities:")
    for ent in annotated_article.entities:
        print(f" - {ent.text_span} ({ent.start_idx}-{ent.end_idx})")

[0, 1, 2, 0, 1, 2, 2, 2, 0, 1, 2, 2, 0, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 2, 2, 2, 0, 0, 0, 2, 0, 0, 1, 2, 0, 2, 0, 1, 1, 2, 0, 0, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 2, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 2, 2, 2, 0, 1, 2, 2, 2, 0, 1, 2, 2, 2, 0, 1, 0, 0, 0, 2, 0, 0, 1]
[0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 2, 2, 2, 0, 1, 0, 0, 0, 1, 2, 2, 0, 1, 0, 0, 1, 2, 2, 2, 2, 2, 0, 1, 2, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 1, 2, 2, 0, 1, 0, 0, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0]
[0, 1, 2, 0, 0, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 2, 0, 0, 1, 2, 0, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 2, 0, 1, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 1, 2, 0, 1, 2, 0, 1, 0, 0, 1, 2, 2, 2, 2, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 2, 1, 2, 2, 2, 2, 2, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 2, 0, 1, 0, 0, 1, 2, 2, 2, 2, 2, 0, 0, 1, 2, 0, 1, 0, 0, 0, 0]
[0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 2, 2, 2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 0, 0, 2, 0, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 1, 2, 2, 2, 2, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 0, 2, 2]
[0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 1, 2, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 2, 1, 0, 0, 0, 0, 1, 0, 1, 1, 2, 2, 2, 2, 1, 2, 2, 0, 0, 0, 1, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 2, 2, 0, 0]
[0, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0]
[0, 0, 0, 1, 2, 2, 2, 2, 2, 0, 1, 2, 0, 0, 0, 1, 2, 2, 0, 0, 1, 2, 2, 2, 2, 2, 2, 0, 1, 0, 2, 0, 0, 1, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 0, 2, 2, 2, 2, 2, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 2, 1, 2, 2, 2, 0, 1, 1, 0, 2, 2, 0, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 0, 0, 0, 1, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2]
[0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 1, 2, 2, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 1, 1, 1, 0, 0, 1, 1, 2, 0, 2, 0, 2, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 0, 1, 2, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0]
Article Orthopedic Surgery Causes Gut Microbiome Dysbiosis and Intestinal Barrier Dysfunction in Prodromal Alzheimer Disease Patients: A Prospective Observational Cohort Study. detected entities:
 - Orthopedic Surgery (0-17)
 - Gut Microbiome Dysbiosis (26-49)
 - Intestinal Barrier Dysfunction (55-84)
 - Prodromal Alzheimer Disease Patients (89-124)
 - gut microbiota (15-28)
 - elderly patients (98-113)
 - NC (145-146)
 - prodromal Alzheimer disease phenotype (154-190)
 - pAD (193-195)
 - subjective cognitive decline (216-243)
 - SCD (246-248)
 - amnestic mild cognitive impairment (254-287)
 - aMCI (290-293)
 - Homeostatic disturbances (297-320)
 - surgical trauma (333-347)
 - stress (356-361)
 - gut microbiota (389-402)
 - elderly patients (439-454)
 - patients (531-538)
 - NC (625-626)
 - SCD (636-638)
 - aMCI (651-654)
 - gut microbiota (670-683)
 - bacterial endotoxin (686-704)
 - lipopolysaccharide (707-724)
 - tight junction (TJ) protein (728-754)
 - inflammatory cytokines (761-782)
 - short-chain fatty acid (SCFA)-producing bacteria (885-932)
 - gram-negative bacteria (955-976)
 - lipopolysaccharide (979-996)
 - TJ (1002-1003)
 - SCD and aMCI (pAD) groups (1044-1068)
 - NC group (1088-1095)
 - SCFA-producing bacteria (1127-1149)
 - gram-negative bacteria (1176-1197)
 - plasma claudin (1203-1216)
 - pAD groups (1242-1251)
 - NC group (1269-1276)
 - SCFA-producing bacteria (1279-1301)
 - cytokines (1342-1350)
 - pAD patients (1355-1366)
 - surgery-induced perioperative metabolic stress (1404-1449)
 - inflammatory responses (1455-1476)
 - gut microbiota alterations (1499-1524)
 - microbiota dysbiosis (1564-1583)
 - intestinal barrier dysfunction (1589-1618)
 - pAD patients (1623-1634)
 - systemic inflammation (1673-1693)
 - cognitive deterioration (1729-1751)
[0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 1, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 1, 0, 0, 0, 1, 2, 2, 2, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 2, 2]
[0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
[0, 1, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 0, 0, 1, 2, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 2, 1, 0, 0, 1, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 2, 2, 2, 0, 1, 2, 2, 2, 0, 1, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2]
[0, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 2, 2, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 2, 0, 0, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 0, 0]
Article Cadmium exposure modulates the gut-liver axis in an Alzheimer's disease mouse model. detected entities:
 - Cadmium exposure (0-15)
 - human Apolipoprotein E4 (4-26)
 - ApoE (29-32)
 - Alzheimer's disease (91-109)
 - AD (112-113)
 - Cadmium (117-123)
 - Cd (126-127)
 - humanized ApoE4 knock-in (ApoE4-KI) mice (198-237)
 - ApoE3 (common allele)-KI mice (254-282)
 - cadmium (309-315)
 - ApoE4 gene variants (332-350)
 - Large intestinal content bacterial 16S rDNA sequencing (382-435)
 - serum lipid metabolomics (438-461)
 - hepatic transcriptomic (468-489)
 - ApoE3- and ApoE4-KI mice (509-532)
 - Cd (591-592)
 - ApoE4-KI males (613-626)
 - gut microbiota (668-681)
 - host liver (812-821)
 - mouse strain (1101-1112)
 - neurological damage (1117-1135)
 - ApoE4-KI males (1148-1161)
 - microbial AD biomarkers (1192-1214)
 - gut (1264-1266)
 - blood (1272-1276)
 - inflammation (1327-1338)
[0, 0, 0, 1, 2, 2, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 1, 2, 2, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 2, 0]
[0, 1, 2, 0, 1, 0, 0, 0, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 2, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 2, 2, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 2, 2, 2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2]
[0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Article Exploring the mycobiota in multiple sclerosis: its influence on disease development and progression. detected entities:
 - mycobiota (14-22)
 - multiple sclerosis (27-44)
 - Multiple sclerosis (0-17)
 - MS (20-21)
 - complex immune-mediated disorder (29-60)
 - gut microbiota (158-171)
 - MS (183-184)
 - fungal microbiota (225-241)
 - mycobiota (244-252)
 - gut mycobiota (308-320)
 - individuals (325-335)
 - MS (342-343)
 - MS patients (538-548)
 - controls (562-569)
 - Saccharomyces (632-644)
 - Torulaspora (654-664)
 - Malassezia (678-687)
 - disability (761-770)
 - neurodegenerative conditions (818-845)
 - MS-associated allele HLA-DRB1*150 (895-927)
 - chitotriosidase (1090-1104)
 - calprotectin (1110-1121)
 - dietary fats (1273-1284)
 - mycobi (1313-1318)
 - MS patients (1338-1348)
 - controls (1358-1365)
 - MS (1409-1410)
 - gut microbiota (1482-1495)
 - MS (1500-1501)
 - MS (1700-1701)
 - mycobiota-targeted therapies (1734-1761)
[0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 1, 1, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 1, 1]
[0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 2, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 2, 2, 0, 1, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 2, 0, 0, 1, 2, 0, 0, 0, 1, 2, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 1, 1, 0, 1, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0, 2, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 2, 0, 0, 0, 0, 2, 2, 0, 0, 1, 0, 1, 0, 2, 2, 0, 0, 2, 0]
[0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 2, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 1, 2, 0, 1, 2, 2, 0, 1, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 1, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0, 2, 2, 0, 0, 2, 2, 2, 0, 0, 0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 1, 0, 0, 1, 1, 2, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 2, 0, 0, 0, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0]
Article Potential benefits of kefir and its compounds on Alzheimer's disease: A systematic review. detected entities:
 - kefi (22-25)
 - compounds (36-44)

In [16]:
from constrerl.utils import prepare_for_eval
from constrerl.eval.evaluate import eval_submission_NED

## Current best:
Full Train + Martinelli params for NED
|   |precision	|recall	    |f1	        |micro_precision	    |micro_recall	|micro_f1	|type
|--|           --|      --|         --|                     --|             --|             --|--
|0	|0.773364	|0.810789	|0.791634	|0.773364	            |0.810789	    |0.791634	|NE

In [17]:


def tuple_to_scores(tup):
    # precision, recall, f1, micro_precision, micro_recall, micro_f1
    return {
        "precision": tup[0],
        "recall": tup[1],
        "f1": tup[2],
        "micro_precision": tup[3],
        "micro_recall": tup[4],
        "micro_f1": tup[5],
    }


# ground_truth_test = {"test": test_article}
eval_functions = {
    "NE": eval_submission_NED,
}
scores_list = []
for typ, eval_fun in eval_functions.items():
    print(f"Evaluating {typ}...")
    scores = eval_fun(
        prepare_for_eval(annotated_articles), prepare_for_eval(ned_dev_articles)
    )
    scores=tuple_to_scores(scores)
    scores["type"] = typ
    scores_list.append(scores)

import pandas as pd
df_scores = pd.DataFrame(scores_list)
df_scores

Evaluating NE...

   precision    recall        f1  micro_precision  micro_recall  micro_f1 type
0   0.774573  0.809599  0.791699         0.774573      0.809599  0.791699   NE

In [18]:
ned_dev_articles['34912029'].entities

[Entity(start_idx=4, end_idx=42, location='abstract', text_span='human Apolipoprotein E4 (ApoE4) variant', label='NE', uri='http://purl.obolibrary.org/obo/NCIT_C105362'),
 Entity(start_idx=91, end_idx=109, location='abstract', text_span="Alzheimer's disease", label='NE', uri='http://purl.obolibrary.org/obo/NCIT_C2866'),
 Entity(start_idx=112, end_idx=113, location='abstract', text_span='AD', label='NE', uri='http://purl.obolibrary.org/obo/NCIT_C2866'),
 Entity(start_idx=117, end_idx=123, location='abstract', text_span='Cadmium', label='NE', uri='http://purl.obolibrary.org/obo/CHEBI_22977'),
 Entity(start_idx=126, end_idx=127, location='abstract', text_span='Cd', label='NE', uri='http://purl.obolibrary.org/obo/CHEBI_22977'),
 Entity(start_idx=198, end_idx=237, location='abstract', text_span='humanized ApoE4 knock-in (ApoE4-KI) mice', label='NE', uri='http://purl.obolibrary.org/obo/NCIT_C45247'),
 Entity(start_idx=254, end_idx=282, location='abstract', text_span='ApoE3 (common allele)-KI mice', label='NE', uri='http://purl.obolibrary.org/obo/NCIT_C45247'),
 Entity(start_idx=309, end_idx=315, location='abstract', text_span='cadmium', label='NE', uri='http://purl.obolibrary.org/obo/CHEBI_22977'),
 Entity(start_idx=332, end_idx=350, location='abstract', text_span='ApoE4 gene variants', label='NE', uri='http://purl.obolibrary.org/obo/NCIT_C105362'),
 Entity(start_idx=382, end_idx=435, location='abstract', text_span='Large intestinal content bacterial 16S rDNA sequencing', label='NE', uri='http://purl.obolibrary.org/obo/OBI_0002763'),
 Entity(start_idx=438, end_idx=461, location='abstract', text_span='serum lipid metabolomics', label='NE', uri='http://w3id.org/hereditary/ontology/gutbrain/resource/H000110'),
 Entity(start_idx=468, end_idx=490, location='abstract', text_span='hepatic transcriptomics', label='NE', uri='http://purl.obolibrary.org/obo/NCIT_C153189'),
 Entity(start_idx=509, end_idx=532, location='abstract', text_span='ApoE3- and ApoE4-KI mice', label='NE', uri='http://purl.obolibrary.org/obo/NCIT_C45247'),
 Entity(start_idx=591, end_idx=592, location='abstract', text_span='Cd', label='NE', uri='http://purl.obolibrary.org/obo/CHEBI_22977'),
 Entity(start_idx=613, end_idx=626, location='abstract', text_span='ApoE4-KI males', label='NE', uri='http://w3id.org/hereditary/ontology/gutbrain/resource/H000005'),
 Entity(start_idx=668, end_idx=681, location='abstract', text_span='gut microbiota', label='NE', uri='http://purl.obolibrary.org/obo/OMIT_0028418'),
 Entity(start_idx=812, end_idx=821, location='abstract', text_span='host liver', label='NE', uri='http://purl.obolibrary.org/obo/NCIT_C12392'),
 Entity(start_idx=824, end_idx=853, location='abstract', text_span='cadmium-exposed ApoE4-KI males', label='NE', uri='http://w3id.org/hereditary/ontology/gutbrain/resource/H000005'),
 Entity(start_idx=1026, end_idx=1027, location='abstract', text_span='Cd', label='NE', uri='http://purl.obolibrary.org/obo/CHEBI_22977'),
 Entity(start_idx=1117, end_idx=1135, location='abstract', text_span='neurological damage', label='NE', uri='http://purl.obolibrary.org/obo/NCIT_C50670'),
 Entity(start_idx=1148, end_idx=1161, location='abstract', text_span='ApoE4-KI males', label='NE', uri='http://w3id.org/hereditary/ontology/gutbrain/resource/H000005'),
 Entity(start_idx=1264, end_idx=1266, location='abstract', text_span='gut', label='NE', uri='http://purl.obolibrary.org/obo/NCIT_C34082'),
 Entity(start_idx=1272, end_idx=1276, location='abstract', text_span='blood', label='NE', uri='http://purl.obolibrary.org/obo/NCIT_C12434'),
 Entity(start_idx=1327, end_idx=1338, location='abstract', text_span='inflammation', label='NE', uri='http://purl.obolibrary.org/obo/NCIT_C3137')]

In [19]:
annotated_articles['34912029'].entities

[Entity(start_idx=0, end_idx=15, location='title', text_span='Cadmium exposure', label='NE', uri=None),
 Entity(start_idx=4, end_idx=26, location='abstract', text_span='human Apolipoprotein E4', label='NE', uri=None),
 Entity(start_idx=29, end_idx=32, location='abstract', text_span='ApoE', label='NE', uri=None),
 Entity(start_idx=91, end_idx=109, location='abstract', text_span="Alzheimer's disease", label='NE', uri=None),
 Entity(start_idx=112, end_idx=113, location='abstract', text_span='AD', label='NE', uri=None),
 Entity(start_idx=117, end_idx=123, location='abstract', text_span='Cadmium', label='NE', uri=None),
 Entity(start_idx=126, end_idx=127, location='abstract', text_span='Cd', label='NE', uri=None),
 Entity(start_idx=198, end_idx=237, location='abstract', text_span='humanized ApoE4 knock-in (ApoE4-KI) mice', label='NE', uri=None),
 Entity(start_idx=254, end_idx=282, location='abstract', text_span='ApoE3 (common allele)-KI mice', label='NE', uri=None),
 Entity(start_idx=309, end_idx=315, location='abstract', text_span='cadmium', label='NE', uri=None),
 Entity(start_idx=332, end_idx=350, location='abstract', text_span='ApoE4 gene variants', label='NE', uri=None),
 Entity(start_idx=382, end_idx=435, location='abstract', text_span='Large intestinal content bacterial 16S rDNA sequencing', label='NE', uri=None),
 Entity(start_idx=438, end_idx=461, location='abstract', text_span='serum lipid metabolomics', label='NE', uri=None),
 Entity(start_idx=468, end_idx=489, location='abstract', text_span='hepatic transcriptomic', label='NE', uri=None),
 Entity(start_idx=509, end_idx=532, location='abstract', text_span='ApoE3- and ApoE4-KI mice', label='NE', uri=None),
 Entity(start_idx=591, end_idx=592, location='abstract', text_span='Cd', label='NE', uri=None),
 Entity(start_idx=613, end_idx=626, location='abstract', text_span='ApoE4-KI males', label='NE', uri=None),
 Entity(start_idx=668, end_idx=681, location='abstract', text_span='gut microbiota', label='NE', uri=None),
 Entity(start_idx=812, end_idx=821, location='abstract', text_span='host liver', label='NE', uri=None),
 Entity(start_idx=1101, end_idx=1112, location='abstract', text_span='mouse strain', label='NE', uri=None),
 Entity(start_idx=1117, end_idx=1135, location='abstract', text_span='neurological damage', label='NE', uri=None),
 Entity(start_idx=1148, end_idx=1161, location='abstract', text_span='ApoE4-KI males', label='NE', uri=None),
 Entity(start_idx=1192, end_idx=1214, location='abstract', text_span='microbial AD biomarkers', label='NE', uri=None),
 Entity(start_idx=1264, end_idx=1266, location='abstract', text_span='gut', label='NE', uri=None),
 Entity(start_idx=1272, end_idx=1276, location='abstract', text_span='blood', label='NE', uri=None),
 Entity(start_idx=1327, end_idx=1338, location='abstract', text_span='inflammation', label='NE', uri=None)]

In [20]:
model.save_pretrained("./finetuned/ned/best_model_pubmed")

In [21]:
tokenizer.save_pretrained("./finetuned/ned/best_model_pubmed")

('./finetuned/ned/best_model_pubmed/tokenizer_config.json',
 './finetuned/ned/best_model_pubmed/special_tokens_map.json',
 './finetuned/ned/best_model_pubmed/vocab.txt',
 './finetuned/ned/best_model_pubmed/added_tokens.json',
 './finetuned/ned/best_model_pubmed/tokenizer.json')