In [446]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [447]:
import sys

sys.path.append("..")

In [448]:

from constrerl.utils import extract_flags_from_name
import glob
from pathlib import Path
import json
import pandas as pd
from collections.abc import Callable, Awaitable

In [449]:
test_file = Path("./results_test/all.csv")
test_df = pd.read_csv(test_file)
report_dir = Path("report")

test_df = test_df[test_df["Team ID"] == "TUGW"]
report_dir = report_dir / "test-tugw"
lbl_xtra = ":test:tugw"
mode = "Merged Test"
# test_df = test_df[test_df["Team ID"] == "ToGS"]
# report_dir = report_dir / "test"
# lbl_xtra = ":test:togs"
# mode = "Test"

report_dir.mkdir(exist_ok=True, parents=True)
test_df

,Team ID,Task ID,Run ID,System Description,macro_precision,macro_recall,macro_f1,micro_precision,micro_recall,micro_f1
93,TUGW,T611,hermesneefinetunedloraentitiesnaivebeamnoneher...,CHASTEGw,0.479636,0.749669,0.576056,0.508341,0.835804,0.632184
94,TUGW,T611,hermesneefinetunedloraentitiesnaivebeamnoneher...,CHASTEGw,0.480541,0.749481,0.576177,0.503820,0.830986,0.627308
95,TUGW,T611,hermesneefinetunedloraentitiesnaivebeamnoneher...,CHASTEGw,0.746095,0.422334,0.523402,0.885235,0.508895,0.646270
96,TUGW,T611,hermesneefinetunedloraentitiesnaivebeamnoneher...,CHASTEGw,0.479682,0.748725,0.575219,0.501346,0.828391,0.624651
97,TUGW,T611,hermesneefinetunedloraentitiesnaivebeamnoneher...,CHASTEGw,0.738384,0.427672,0.524773,0.868801,0.512973,0.645071
98,TUGW,T611,hermesneefinetunedloraentitiesnaivebeamnoneher...,CHASTEGw,0.478801,0.748708,0.575115,0.505626,0.832839,0.629236
99,TUGW,T611,hermesneefinetunedloraentitiesnaivebeamnoneher...,CHASTEGw,0.337742,0.455759,0.372688,0.334025,0.537064,0.411882
100,TUGW,T611,hermesneefinetunedloraentitiesnaivebeamnoneher...,CHASTEGw,0.337742,0.455759,0.372688,0.334025,0.537064,0.411882
101,TUGW,T611,naiveentitiesGraphwiseT61113NEREXP8SUB1union,NaiveGw,0.476505,0.754267,0.575251,0.527171,0.841364,0.648201
102,TUGW,T611,naiveentitiesGraphwiseT61124ENSEXP4SUB1union,NaiveGw,0.476359,0.754236,0.574762,0.523898,0.836916,0.644406
103,TUGW,T611,naiveentitiesGraphwiseT612224ENSEXP4SUB1ELfreq...,NaiveGw,0.746246,0.422334,0.523440,0.885806,0.508895,0.646422
104,TUGW,T611,naiveentitiesGraphwiseT612224ENSEXP4SUB1ELfreq...,NaiveGw,0.475719,0.754395,0.574374,0.522042,0.833951,0.642123
105,TUGW,T611,naiveentitiesGraphwiseT612313NEREXP8SUB1ELfreq...,NaiveGw,0.738530,0.427672,0.524811,0.869347,0.512973,0.645221
106,TUGW,T611,naiveentitiesGraphwiseT612313NEREXP8SUB1ELfreq...,NaiveGw,0.475611,0.753100,0.574278,0.525081,0.838028,0.645631
107,TUGW,T611,naiveentitiesGraphwiseT621BGPT5520Ggpt5.520sho...,NaiveGw,0.308520,0.460152,0.357697,0.355965,0.544107,0.430372
108,TUGW,T611,naiveentitiesGraphwiseT622BGPT5520Ggpt5.520sho...,NaiveGw,0.308520,0.460152,0.357697,0.355965,0.544107,0.430372
209,TUGW,T612,hermesneefinetunedloraentitiesnaivebeamnoneher...,CHASTEGw,0.115336,0.181533,0.138571,0.129170,0.212380,0.160639
210,TUGW,T612,hermesneefinetunedloraentitiesnaivebeamnoneher...,CHASTEGw,0.118442,0.184856,0.141744,0.130112,0.214603,0.162003
211,TUGW,T612,hermesneefinetunedloraentitiesnaivebeamnoneher...,CHASTEGw,0.634085,0.362610,0.446934,0.771760,0.443662,0.563427
212,TUGW,T612,hermesneefinetunedloraentitiesnaivebeamnoneher...,CHASTEGw,0.266929,0.422164,0.321122,0.303499,0.501483,0.378144
213,TUGW,T612,hermesneefinetunedloraentitiesnaivebeamnoneher...,CHASTEGw,0.628193,0.367584,0.448442,0.757690,0.447368,0.562573
214,TUGW,T612,hermesneefinetunedloraentitiesnaivebeamnoneher...,CHASTEGw,0.270040,0.428799,0.325824,0.306256,0.504448,0.381126
215,TUGW,T612,hermesneefinetunedloraentitiesnaivebeamnoneher...,CHASTEGw,0.241557,0.316783,0.262079,0.236745,0.380652,0.291927
216,TUGW,T612,hermesneefinetunedloraentitiesnaivebeamnoneher...,CHASTEGw,0.241557,0.316783,0.262079,0.236745,0.380652,0.291927
217,TUGW,T612,naiveentitiesGraphwiseT61113NEREXP8SUB1union,NaiveGw,0.111043,0.176248,0.133906,0.128425,0.204967,0.157910
218,TUGW,T612,naiveentitiesGraphwiseT61124ENSEXP4SUB1union,NaiveGw,0.113576,0.179313,0.136622,0.129698,0.207191,0.159532
219,TUGW,T612,naiveentitiesGraphwiseT612224ENSEXP4SUB1ELfreq...,NaiveGw,0.634220,0.362610,0.446969,0.772258,0.443662,0.563559
220,TUGW,T612,naiveentitiesGraphwiseT612224ENSEXP4SUB1ELfreq...,NaiveGw,0.263035,0.420767,0.318001,0.314617,0.502595,0.386986
221,TUGW,T612,naiveentitiesGraphwiseT612313NEREXP8SUB1ELfreq...,NaiveGw,0.628324,0.367584,0.448476,0.758166,0.447368,0.562704
222,TUGW,T612,naiveentitiesGraphwiseT612313NEREXP8SUB1ELfreq...,NaiveGw,0.266644,0.426565,0.322710,0.316071,0.504448,0.388635
223,TUGW,T612,naiveentitiesGraphwiseT621BGPT5520Ggpt5.520sho...,NaiveGw,0.218653,0.315872,0.249304,0.250242,0.382506,0.302551
224,TUGW,T612,naiveentitiesGraphwiseT622BGPT5520Ggpt5.520sho...,NaiveGw,0.218653,0.315872,0.249304,0.250242,0.382506,0.302551
414,TUGW,T622,hermeslorasbeamnonehermes323BsGraphwiseT61113N...,CHASTEGw,0.028328,0.038632,0.026640,0.060232,0.068313,0.064019
415,TUGW,T622,hermeslorasbeamnonehermes323BsGraphwiseT61124E...,CHASTEGw,0.028328,0.038632,0.026640,0.060232,0.068313,0.064019
416,TUGW,T622,hermeslorasbeamnonehermes323BsGraphwiseT612224...,CHASTEGw,0.028328,0.038632,0.026640,0.060232,0.068313,0.064019
417,TUGW,T622,hermeslorasbeamnonehermes323BsGraphwiseT612313...,CHASTEGw,0.028328,0.038632,0.026640,0.060232,0.068313,0.064019
418,TUGW,T622,hermeslorasbeamnonehermes323BsGraphwiseT622BGP...,CHASTEGw,0.045630,0.009004,0.014492,0.341176,0.023868,0.044615
419,TUGW,T622,hermeslorasbeamnonehermes323BsGraphwiseT622BGP...,CHASTEGw,0.073661,0.204653,0.099398,0.085140,0.219753,0.122730

In [450]:
eval_results: list[dict] = []


score_map = {
    "macro_precision": "$P$",
    "macro_recall": "$R$",
    "macro_f1": "$F_1$",
    "micro_precision": "$P_{micro}$",
    "micro_recall": "$R_{micro}$",
    "micro_f1": "$F_{1,micro}$",
}


def test_table_to_df(
    table: pd.DataFrame,
    task: str,
) -> pd.DataFrame:
    eval_results = []
    for i, row in table.iterrows():
        run_id: str = row["Run ID"]
        merge_mode = row["Team ID"] == "TUGW"
        if row["Task ID"] != task:
            continue
        eval_result = {f"{k}": v for k, v in row.items() if k in score_map}

        result_dict = extract_flags_from_name(
            run_id, merge_mode=merge_mode, k=None, test_mode=True
        )
        result_dict.update(eval_result)
        eval_results.append(result_dict)
    if len(eval_results) == 0:
        return pd.DataFrame()
    eval_df = pd.DataFrame(eval_results)
    # remove duplicate rows
    eval_df = eval_df.drop_duplicates()
    eval_df.rename(score_map, axis=1, inplace=True)
    valid_cols = [
        c
        for c in [
            "Graphwise",
            "Set",
            "Model",
            "Beams",
            "NED FT",
            "RAG",
            "LoRA",
            "Naive",
            "Filter",
        ]
        if c in eval_df.columns
    ]
    eval_df.set_index(valid_cols, inplace=True)
    eval_df = eval_df.sort_index()
    # if "$F_{1,micro}$" in eval_df.columns:
    #     eval_df = eval_df.sort_values("$F_{1,micro}$")
    return eval_df


task_6_1_1_df = test_table_to_df(test_df, "T611")
task_6_1_2_df = test_table_to_df(test_df, "T612")
task_6_2_1_df = test_table_to_df(test_df, "T621")
task_6_2_2_df = test_table_to_df(test_df, "T622")
task_6_1_1_df

Looking for submission file for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT61113NEREXP8SUB1union, found staging/TUGW_T612_hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT61113NEREXP8SUB1union_CHASTEGw
Found full run id ['eval_hermes_neefinetuned-lora-entities-naive-beam-none-hermes-3-2-3B-entities_Graphwise_T611_13_NER-EXP-8-SUB-1_union'] for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT61113NEREXP8SUB1union
Looking for submission file for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT61124ENSEXP4SUB1union, found staging/TUGW_T612_hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT61124ENSEXP4SUB1union_CHASTEGw
Found full run id ['eval_hermes_neefinetuned-lora-entities-naive-beam-none-hermes-3-2-3B-entities_Graphwise_T611_24_ENS-EXP-4-SUB-1_union'] for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT61124ENSEXP4SUB1union
Looking for submission file for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeintersection, found staging/TUGW_T611_hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeintersection_CHASTEGw
Found full run id ['eval_hermes_neefinetuned-lora-entities-naive-beam-none-hermes-3-2-3B-entities_Graphwise_T612_2_24-ENS-EXP-4-SUB-1-EL-freq-gaze_intersection'] for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeintersection
Looking for submission file for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeunion, found staging/TUGW_T611_hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeunion_CHASTEGw
Found full run id ['eval_hermes_neefinetuned-lora-entities-naive-beam-none-hermes-3-2-3B-entities_Graphwise_T612_2_24-ENS-EXP-4-SUB-1-EL-freq-gaze_union'] for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeunion
Looking for submission file for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeintersection, found staging/TUGW_T612_hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeintersection_CHASTEGw
Found full run id ['eval_hermes_neefinetuned-lora-entities-naive-beam-none-hermes-3-2-3B-entities_Graphwise_T612_3_13-NER-EXP-8-SUB-1-EL-freq-gaze_intersection'] for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeintersection
Looking for submission file for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeunion, found staging/TUGW_T612_hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeunion_CHASTEGw
Found full run id ['eval_hermes_neefinetuned-lora-entities-naive-beam-none-hermes-3-2-3B-entities_Graphwise_T612_3_13-NER-EXP-8-SUB-1-EL-freq-gaze_union'] for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeunion
Looking for submission file for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT621BGPT5520Ggpt5.520shotgoldunion, found staging/TUGW_T612_hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT621BGPT5520Ggpt5.520shotgoldunion_CHASTEGw
Found full run id ['eval_hermes_neefinetuned-lora-entities-naive-beam-none-hermes-3-2-3B-entities_Graphwise_T621_BGPT5520G_gpt-5.5_20_shot_gold_union'] for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT621BGPT5520Ggpt5.520shotgoldunion
Looking for submission file for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT622BGPT5520Ggpt5.520shotgoldunion, found staging/TUGW_T612_hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT622BGPT5520Ggpt5.520shotgoldunion_CHASTEGw
Found full run id ['eval_hermes_neefinetuned-lora-entities-naive-beam-none-hermes-3-2-3B-entities_Graphwise_T622_BGPT5520G_gpt-5.5_20_shot_gold_union'] for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT622BGPT5520Ggpt5.520shotgoldunion
Looking for submission file for naiveentitiesGraphwiseT61113NEREXP8SUB1union, found staging/TUGW_T611_naiveentitiesGraphwiseT61113NEREXP8SUB1union_NaiveGw
Found full run id ['eval_naive-entities_Graphwise_T611_13_NER-EXP-8-SUB-1_union'] for naiveentitiesGraphwiseT61113NEREXP8SUB1union
Looking for submission file for naiveentitiesGraphwiseT61124ENSEXP4SUB1union, found staging/TUGW_T612_naiveentitiesGraphwiseT61124ENSEXP4SUB1union_NaiveGw
Found full run id ['eval_naive-entities_Graphwise_T611_24_ENS-EXP-4-SUB-1_union'] for naiveentitiesGraphwiseT61124ENSEXP4SUB1union
Looking for submission file for naiveentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeintersection, found staging/TUGW_T612_naiveentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeintersection_NaiveGw
Found full run id ['eval_naive-entities_Graphwise_T612_2_24-ENS-EXP-4-SUB-1-EL-freq-gaze_intersection'] for naiveentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeintersection
Looking for submission file for naiveentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeunion, found staging/TUGW_T612_naiveentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeunion_NaiveGw
Found full run id ['eval_naive-entities_Graphwise_T612_2_24-ENS-EXP-4-SUB-1-EL-freq-gaze_union'] for naiveentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeunion
Looking for submission file for naiveentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeintersection, found staging/TUGW_T612_naiveentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeintersection_NaiveGw
Found full run id ['eval_naive-entities_Graphwise_T612_3_13-NER-EXP-8-SUB-1-EL-freq-gaze_intersection'] for naiveentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeintersection
Looking for submission file for naiveentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeunion, found staging/TUGW_T611_naiveentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeunion_NaiveGw
Found full run id ['eval_naive-entities_Graphwise_T612_3_13-NER-EXP-8-SUB-1-EL-freq-gaze_union'] for naiveentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeunion
Looking for submission file for naiveentitiesGraphwiseT621BGPT5520Ggpt5.520shotgoldunion, found staging/TUGW_T611_naiveentitiesGraphwiseT621BGPT5520Ggpt5.520shotgoldunion_NaiveGw
Found full run id ['eval_naive-entities_Graphwise_T621_BGPT5520G_gpt-5.5_20_shot_gold_union'] for naiveentitiesGraphwiseT621BGPT5520Ggpt5.520shotgoldunion
Looking for submission file for naiveentitiesGraphwiseT622BGPT5520Ggpt5.520shotgoldunion, found staging/TUGW_T611_naiveentitiesGraphwiseT622BGPT5520Ggpt5.520shotgoldunion_NaiveGw
Found full run id ['eval_naive-entities_Graphwise_T622_BGPT5520G_gpt-5.5_20_shot_gold_union'] for naiveentitiesGraphwiseT622BGPT5520Ggpt5.520shotgoldunion
Looking for submission file for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT61113NEREXP8SUB1union, found staging/TUGW_T612_hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT61113NEREXP8SUB1union_CHASTEGw
Found full run id ['eval_hermes_neefinetuned-lora-entities-naive-beam-none-hermes-3-2-3B-entities_Graphwise_T611_13_NER-EXP-8-SUB-1_union'] for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT61113NEREXP8SUB1union
Looking for submission file for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT61124ENSEXP4SUB1union, found staging/TUGW_T612_hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT61124ENSEXP4SUB1union_CHASTEGw
Found full run id ['eval_hermes_neefinetuned-lora-entities-naive-beam-none-hermes-3-2-3B-entities_Graphwise_T611_24_ENS-EXP-4-SUB-1_union'] for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT61124ENSEXP4SUB1union
Looking for submission file for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeintersection, found staging/TUGW_T611_hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeintersection_CHASTEGw
Found full run id ['eval_hermes_neefinetuned-lora-entities-naive-beam-none-hermes-3-2-3B-entities_Graphwise_T612_2_24-ENS-EXP-4-SUB-1-EL-freq-gaze_intersection'] for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeintersection
Looking for submission file for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeunion, found staging/TUGW_T611_hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeunion_CHASTEGw
Found full run id ['eval_hermes_neefinetuned-lora-entities-naive-beam-none-hermes-3-2-3B-entities_Graphwise_T612_2_24-ENS-EXP-4-SUB-1-EL-freq-gaze_union'] for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeunion
Looking for submission file for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeintersection, found staging/TUGW_T612_hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeintersection_CHASTEGw
Found full run id ['eval_hermes_neefinetuned-lora-entities-naive-beam-none-hermes-3-2-3B-entities_Graphwise_T612_3_13-NER-EXP-8-SUB-1-EL-freq-gaze_intersection'] for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeintersection
Looking for submission file for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeunion, found staging/TUGW_T612_hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeunion_CHASTEGw
Found full run id ['eval_hermes_neefinetuned-lora-entities-naive-beam-none-hermes-3-2-3B-entities_Graphwise_T612_3_13-NER-EXP-8-SUB-1-EL-freq-gaze_union'] for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeunion
Looking for submission file for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT621BGPT5520Ggpt5.520shotgoldunion, found staging/TUGW_T612_hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT621BGPT5520Ggpt5.520shotgoldunion_CHASTEGw
Found full run id ['eval_hermes_neefinetuned-lora-entities-naive-beam-none-hermes-3-2-3B-entities_Graphwise_T621_BGPT5520G_gpt-5.5_20_shot_gold_union'] for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT621BGPT5520Ggpt5.520shotgoldunion
Looking for submission file for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT622BGPT5520Ggpt5.520shotgoldunion, found staging/TUGW_T612_hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT622BGPT5520Ggpt5.520shotgoldunion_CHASTEGw
Found full run id ['eval_hermes_neefinetuned-lora-entities-naive-beam-none-hermes-3-2-3B-entities_Graphwise_T622_BGPT5520G_gpt-5.5_20_shot_gold_union'] for hermesneefinetunedloraentitiesnaivebeamnonehermes323BentitiesGraphwiseT622BGPT5520Ggpt5.520shotgoldunion
Looking for submission file for naiveentitiesGraphwiseT61113NEREXP8SUB1union, found staging/TUGW_T611_naiveentitiesGraphwiseT61113NEREXP8SUB1union_NaiveGw
Found full run id ['eval_naive-entities_Graphwise_T611_13_NER-EXP-8-SUB-1_union'] for naiveentitiesGraphwiseT61113NEREXP8SUB1union
Looking for submission file for naiveentitiesGraphwiseT61124ENSEXP4SUB1union, found staging/TUGW_T612_naiveentitiesGraphwiseT61124ENSEXP4SUB1union_NaiveGw
Found full run id ['eval_naive-entities_Graphwise_T611_24_ENS-EXP-4-SUB-1_union'] for naiveentitiesGraphwiseT61124ENSEXP4SUB1union
Looking for submission file for naiveentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeintersection, found staging/TUGW_T612_naiveentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeintersection_NaiveGw
Found full run id ['eval_naive-entities_Graphwise_T612_2_24-ENS-EXP-4-SUB-1-EL-freq-gaze_intersection'] for naiveentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeintersection
Looking for submission file for naiveentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeunion, found staging/TUGW_T612_naiveentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeunion_NaiveGw
Found full run id ['eval_naive-entities_Graphwise_T612_2_24-ENS-EXP-4-SUB-1-EL-freq-gaze_union'] for naiveentitiesGraphwiseT612224ENSEXP4SUB1ELfreqgazeunion
Looking for submission file for naiveentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeintersection, found staging/TUGW_T612_naiveentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeintersection_NaiveGw
Found full run id ['eval_naive-entities_Graphwise_T612_3_13-NER-EXP-8-SUB-1-EL-freq-gaze_intersection'] for naiveentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeintersection
Looking for submission file for naiveentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeunion, found staging/TUGW_T611_naiveentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeunion_NaiveGw
Found full run id ['eval_naive-entities_Graphwise_T612_3_13-NER-EXP-8-SUB-1-EL-freq-gaze_union'] for naiveentitiesGraphwiseT612313NEREXP8SUB1ELfreqgazeunion
Looking for submission file for naiveentitiesGraphwiseT621BGPT5520Ggpt5.520shotgoldunion, found staging/TUGW_T611_naiveentitiesGraphwiseT621BGPT5520Ggpt5.520shotgoldunion_NaiveGw
Found full run id ['eval_naive-entities_Graphwise_T621_BGPT5520G_gpt-5.5_20_shot_gold_union'] for naiveentitiesGraphwiseT621BGPT5520Ggpt5.520shotgoldunion
Looking for submission file for naiveentitiesGraphwiseT622BGPT5520Ggpt5.520shotgoldunion, found staging/TUGW_T611_naiveentitiesGraphwiseT622BGPT5520Ggpt5.520shotgoldunion_NaiveGw
Found full run id ['eval_naive-entities_Graphwise_T622_BGPT5520G_gpt-5.5_20_shot_gold_union'] for naiveentitiesGraphwiseT622BGPT5520Ggpt5.520shotgoldunion
Looking for submission file for hermeslorasbeamnonehermes323BsGraphwiseT61113NEREXP8SUB1union, found staging/TUGW_T622_hermeslorasbeamnonehermes323BsGraphwiseT61113NEREXP8SUB1union_CHASTEGw
Found full run id ['eval_hermes-lora-relations-beam-none-hermes-3-2-3B-relations_Graphwise_T611_13_NER-EXP-8-SUB-1_union'] for hermeslorasbeamnonehermes323BsGraphwiseT61113NEREXP8SUB1union
Looking for submission file for hermeslorasbeamnonehermes323BsGraphwiseT61124ENSEXP4SUB1union, found staging/TUGW_T622_hermeslorasbeamnonehermes323BsGraphwiseT61124ENSEXP4SUB1union_CHASTEGw
Found full run id ['eval_hermes-lora-relations-beam-none-hermes-3-2-3B-relations_Graphwise_T611_24_ENS-EXP-4-SUB-1_union'] for hermeslorasbeamnonehermes323BsGraphwiseT61124ENSEXP4SUB1union
Looking for submission file for hermeslorasbeamnonehermes323BsGraphwiseT612224ENSEXP4SUB1ELfreqgazeunion, found staging/TUGW_T622_hermeslorasbeamnonehermes323BsGraphwiseT612224ENSEXP4SUB1ELfreqgazeunion_CHASTEGw
Found full run id ['eval_hermes-lora-relations-beam-none-hermes-3-2-3B-relations_Graphwise_T612_2_24-ENS-EXP-4-SUB-1-EL-freq-gaze_union'] for hermeslorasbeamnonehermes323BsGraphwiseT612224ENSEXP4SUB1ELfreqgazeunion
Looking for submission file for hermeslorasbeamnonehermes323BsGraphwiseT612313NEREXP8SUB1ELfreqgazeunion, found staging/TUGW_T622_hermeslorasbeamnonehermes323BsGraphwiseT612313NEREXP8SUB1ELfreqgazeunion_CHASTEGw
Found full run id ['eval_hermes-lora-relations-beam-none-hermes-3-2-3B-relations_Graphwise_T612_3_13-NER-EXP-8-SUB-1-EL-freq-gaze_union'] for hermeslorasbeamnonehermes323BsGraphwiseT612313NEREXP8SUB1ELfreqgazeunion
Looking for submission file for hermeslorasbeamnonehermes323BsGraphwiseT622BGPT5520Ggpt5.520shotgoldintersection, found staging/TUGW_T622_hermeslorasbeamnonehermes323BsGraphwiseT622BGPT5520Ggpt5.520shotgoldintersection_CHASTEGw
Found full run id ['eval_hermes-lora-relations-beam-none-hermes-3-2-3B-relations_Graphwise_T622_BGPT5520G_gpt-5.5_20_shot_gold_intersection'] for hermeslorasbeamnonehermes323BsGraphwiseT622BGPT5520Ggpt5.520shotgoldintersection
Looking for submission file for hermeslorasbeamnonehermes323BsGraphwiseT622BGPT5520Ggpt5.520shotgoldunion, found staging/TUGW_T622_hermeslorasbeamnonehermes323BsGraphwiseT622BGPT5520Ggpt5.520shotgoldunion_CHASTEGw
Found full run id ['eval_hermes-lora-relations-beam-none-hermes-3-2-3B-relations_Graphwise_T622_BGPT5520G_gpt-5.5_20_shot_gold_union'] for hermeslorasbeamnonehermes323BsGraphwiseT622BGPT5520Ggpt5.520shotgoldunion

                                                                                                                          $P$  \
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.480541
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.476359
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.746095
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.746246
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.479682
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.475719
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.479636
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.476505
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.738384
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.738530
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.478801
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.475611
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.337742
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.308520

                                                                                                                          $R$  \
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.749481
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.754236
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.422334
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.422334
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.748725
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.754395
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.749669
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.754267
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.427672
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.427672
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.748708
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.753100
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.455759
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.460152

                                                                                                                        $F_1$  \
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.576177
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.574762
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.523402
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.523440
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.575219
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.574374
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.576056
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.575251
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.524773
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.524811
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.575115
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.574278
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.372688
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.357697

                                                                                                                     $P_{micro}$  \
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.503820
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.523898
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.885235
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.885806
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.501346
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.522042
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.508341
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.527171
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.868801
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.869347
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.505626
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.525081
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.334025
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.355965

                                                                                                                     $R_{micro}$  \
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.830986
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.836916
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.508895
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.508895
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.828391
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.833951
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.835804
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.841364
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.512973
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.512973
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.832839
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.838028
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.537064
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.544107

                                                                                                                     $F_{1,micro}$
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.627308
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.644406
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.646270
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.646422
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.624651
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.642123
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.632184
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.648201
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.645071
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.645221
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.629236
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.645631
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.411882
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.430372

In [451]:
task_6_1_1_df

                                                                                                                          $P$  \
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.480541
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.476359
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.746095
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.746246
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.479682
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.475719
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.479636
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.476505
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.738384
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.738530
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.478801
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.475611
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.337742
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.308520

                                                                                                                          $R$  \
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.749481
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.754236
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.422334
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.422334
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.748725
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.754395
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.749669
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.754267
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.427672
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.427672
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.748708
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.753100
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.455759
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.460152

                                                                                                                        $F_1$  \
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.576177
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.574762
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.523402
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.523440
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.575219
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.574374
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.576056
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.575251
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.524773
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.524811
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.575115
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.574278
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.372688
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.357697

                                                                                                                     $P_{micro}$  \
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.503820
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.523898
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.885235
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.885806
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.501346
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.522042
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.508341
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.527171
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.868801
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.869347
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.505626
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.525081
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.334025
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.355965

                                                                                                                     $R_{micro}$  \
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.830986
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.836916
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.508895
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.508895
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.828391
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.833951
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.835804
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.841364
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.512973
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.512973
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.832839
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.838028
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.537064
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.544107

                                                                                                                     $F_{1,micro}$
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.627308
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.644406
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.646270
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.646422
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.624651
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.642123
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.632184
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.648201
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.645071
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.645221
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.629236
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.645631
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.411882
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.430372

In [452]:
task_6_1_1_df.style.highlight_max(axis=0, props="textbf:--rwrap;").format(precision=2).to_latex(
    report_dir / "task_6_1_1.tex",
    # float_format="%.2f",
    caption=f"{mode} Set Result for Task 6.1.1 for various models and approaches.",
    label=f"tab:task:6_1_1{lbl_xtra}",
    clines="all;data",
    hrules=True
)
task_6_1_1_df

                                                                                                                          $P$  \
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.480541
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.476359
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.746095
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.746246
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.479682
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.475719
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.479636
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.476505
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.738384
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.738530
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.478801
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.475611
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.337742
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.308520

                                                                                                                          $R$  \
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.749481
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.754236
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.422334
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.422334
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.748725
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.754395
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.749669
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.754267
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.427672
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.427672
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.748708
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.753100
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.455759
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.460152

                                                                                                                        $F_1$  \
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.576177
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.574762
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.523402
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.523440
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.575219
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.574374
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.576056
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.575251
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.524773
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.524811
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.575115
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.574278
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.372688
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.357697

                                                                                                                     $P_{micro}$  \
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.503820
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.523898
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.885235
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.885806
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.501346
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.522042
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.508341
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.527171
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.868801
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.869347
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.505626
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.525081
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.334025
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.355965

                                                                                                                     $R_{micro}$  \
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.830986
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.836916
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.508895
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.508895
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.828391
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.833951
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.835804
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.841364
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.512973
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.512973
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.832839
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.838028
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.537064
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.544107

                                                                                                                     $F_{1,micro}$
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.627308
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.644406
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.646270
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.646422
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.624651
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.642123
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.632184
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.648201
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.645071
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.645221
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.629236
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.645631
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.411882
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.430372

In [453]:
task_6_1_2_df.style.highlight_max(axis=0, props="textbf:--rwrap;").format(precision=2).to_latex(
    report_dir / "task_6_1_2.tex",
    # float_format="%.2f",
    caption=f"{mode} Set Result for Task 6.1.2 for various models and approaches.",
    label=f"tab:task:6_1_2{lbl_xtra}",
    clines="all;data",
    hrules=True
)
task_6_1_2_df

                                                                                                                          $P$  \
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.118442
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.113576
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.634085
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.634220
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.266929
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.263035
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.115336
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.111043
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.628193
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.628324
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.270040
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.266644
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.241557
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.218653

                                                                                                                          $R$  \
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.184856
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.179313
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.362610
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.362610
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.422164
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.420767
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.181533
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.176248
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.367584
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.367584
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.428799
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.426565
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.316783
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.315872

                                                                                                                        $F_1$  \
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.141744
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.136622
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.446934
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.446969
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.321122
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.318001
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.138571
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.133906
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.448442
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.448476
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.325824
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.322710
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark  0.262079
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark  0.249304

                                                                                                                     $P_{micro}$  \
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.130112
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.129698
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.771760
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.772258
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.303499
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.314617
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.129170
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.128425
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.757690
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.758166
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.306256
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.316071
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.236745
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.250242

                                                                                                                     $R_{micro}$  \
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.214603
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.207191
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.443662
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.443662
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.501483
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.502595
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.212380
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.204967
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.447368
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.447368
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.504448
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.504448
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark     0.380652
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark     0.382506

                                                                                                                     $F_{1,micro}$
Graphwise                                          Set    Model  Beams    NED FT     RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.162003
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.159532
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.563427
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.563559
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.378144
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.386986
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.160639
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.157910
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cap$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.562573
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.562704
                                                   $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.381126
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.388635
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cup$ 3.2 3B $\times$ \checkmark $\times$ \checkmark \checkmark       0.291927
                                                          Naive  $\times$ $\times$   $\times$ $\times$   \checkmark       0.302551

In [454]:
task_6_2_1_df.style.highlight_max(axis=0, props="textbf:--rwrap;").format(precision=2).to_latex(
    report_dir / "task_6_2_1.tex",
    # float_format="%.2f",
    caption=f"{mode} Set Result for Task 6.2.1 for various models and approaches.",
    label=f"tab:task:6_2_1{lbl_xtra}",
    clines="all;data",
    hrules=True
)
task_6_2_1_df

Empty DataFrame
Columns: []
Index: []

In [455]:
task_6_2_2_df

                                                                                                                      $P$  \
Graphwise                                          Set    Model  Beams    NED FT   RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.028328
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.028328
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.028328
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.028328
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cap$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.045630
                                                   $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.073661

                                                                                                                      $R$  \
Graphwise                                          Set    Model  Beams    NED FT   RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.038632
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.038632
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.038632
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.038632
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cap$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.009004
                                                   $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.204653

                                                                                                                    $F_1$  \
Graphwise                                          Set    Model  Beams    NED FT   RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.026640
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.026640
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.026640
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.026640
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cap$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.014492
                                                   $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.099398

                                                                                                                 $P_{micro}$  \
Graphwise                                          Set    Model  Beams    NED FT   RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.060232
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.060232
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.060232
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.060232
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cap$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.341176
                                                   $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.085140

                                                                                                                 $R_{micro}$  \
Graphwise                                          Set    Model  Beams    NED FT   RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.068313
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.068313
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.068313
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.068313
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cap$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.023868
                                                   $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.219753

                                                                                                                 $F_{1,micro}$
Graphwise                                          Set    Model  Beams    NED FT   RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$       0.064019
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$       0.064019
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$       0.064019
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$       0.064019
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cap$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$       0.044615
                                                   $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$       0.122730

In [456]:
task_6_2_2_df.style.highlight_max(axis=0, props="textbf:--rwrap;").format(precision=2).to_latex(
    report_dir / "task_6_2_2.tex",
    # float_format="%.2f",
    caption=f"{mode} Set Result for Task 6.2.2 for various models and approaches.",
    label=f"tab:task:6_2_2{lbl_xtra}",
    clines="all;data",
    hrules=True
)
task_6_2_2_df

                                                                                                                      $P$  \
Graphwise                                          Set    Model  Beams    NED FT   RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.028328
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.028328
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.028328
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.028328
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cap$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.045630
                                                   $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.073661

                                                                                                                      $R$  \
Graphwise                                          Set    Model  Beams    NED FT   RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.038632
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.038632
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.038632
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.038632
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cap$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.009004
                                                   $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.204653

                                                                                                                    $F_1$  \
Graphwise                                          Set    Model  Beams    NED FT   RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.026640
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.026640
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.026640
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.026640
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cap$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.014492
                                                   $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$  0.099398

                                                                                                                 $P_{micro}$  \
Graphwise                                          Set    Model  Beams    NED FT   RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.060232
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.060232
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.060232
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.060232
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cap$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.341176
                                                   $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.085140

                                                                                                                 $R_{micro}$  \
Graphwise                                          Set    Model  Beams    NED FT   RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.068313
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.068313
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.068313
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.068313
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cap$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.023868
                                                   $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$     0.219753

                                                                                                                 $F_{1,micro}$
Graphwise                                          Set    Model  Beams    NED FT   RAG      LoRA       Naive
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$       0.064019
\parbox{2cm}{\vspace*{0.3em}ENS-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$       0.064019
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-1\vspac... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$       0.064019
\parbox{2cm}{\vspace*{0.3em}NER-EXP-SUB-EL-freq... $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$       0.064019
\parbox{2cm}{\vspace*{0.3em}gpt-5.shot-gold\vsp... $\cap$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$       0.044615
                                                   $\cup$ 3.2 3B $\times$ $\times$ $\times$ \checkmark $\times$       0.122730

In [457]:
task_6_1_1_df.columns

Index(['$P$', '$R$', '$F_1$', '$P_{micro}$', '$R_{micro}$', '$F_{1,micro}$'], dtype='object')

In [458]:
tasks = {
    "6.1.1": task_6_1_1_df,
    "6.1.2": task_6_1_2_df,
    "6.2.1": task_6_2_1_df,
    "6.2.2": task_6_2_2_df,
}
average_improvements = []

import re

from constrerl.utils import calculate_improvements, df_topk




for task_name, task_df in tasks.items():
    if len(task_df) == 0:
        print(f"No results for Task {task_name}, skipping.")
        continue
    print(f"Processing Task {task_name} with {len(task_df)} results.")
    task_name_formatted = re.sub(r"\.", "_", task_name)

    task_df.style.highlight_max(axis=0, props="textbf:--rwrap;").format(
        lambda v: f"{v:.2f}" if isinstance(v, float) else v
    ).to_latex(
        report_dir / f"task_{task_name_formatted}_full.tex",
        caption=f"{mode} Set Results for Task {task_name}",
        label=f"tab:task:{task_name_formatted}{lbl_xtra}:full",
        clines="all;data",
        hrules=True,
    )
    top_k = 10
    task_df_top = df_topk(task_df, top_k)
    task_df_top.style.highlight_max(axis=0, props="textbf:--rwrap;").format(
        lambda v: f"{v:.2f}" if isinstance(v, float) else v
    ).to_latex(
        report_dir / f"task_{task_name_formatted}_top.tex",
        caption=f"Top {top_k} {mode} Set Results for Task {task_name}",
        label=f"tab:task:{task_name_formatted}{lbl_xtra}",
        clines="all;data",
        hrules=True,
    )
    task_df_improved = calculate_improvements(task_df)
    mean_improvements = task_df_improved.mean()

    task_df_improved.style.format(
        lambda v: (
            f"+\\textcolor{{DarkGreen}}{{{v:.2f}}}"
            if v > 0
            else f"\\textcolor{{DarkRed}}{{{v:.2f}}}"
            if isinstance(v, float)
            else v
        )
    ).to_latex(
        report_dir / f"task_{task_name_formatted}_improve.tex",
        caption=f"{mode} Set Improvements for Task {task_name}",
        label=f"tab:task:{task_name_formatted}{lbl_xtra}_improve",
        clines="all;data",
        hrules=True,
    )
    average_improvements.append(mean_improvements.to_dict() | {"Task": task_name})

Processing Task 6.1.1 with 14 results.
Calculating improvements based on keys: ['Beams'] with options: [('Beams', [])] / other keys: ['Graphwise', 'Set', 'Model', 'NED FT', 'RAG', 'LoRA', 'Naive']
No improvements calculated. Returning empty DataFrame.
Processing Task 6.1.2 with 14 results.
Calculating improvements based on keys: ['Beams'] with options: [('Beams', [])] / other keys: ['Graphwise', 'Set', 'Model', 'NED FT', 'RAG', 'LoRA', 'Naive']
No improvements calculated. Returning empty DataFrame.
No results for Task 6.2.1, skipping.
Processing Task 6.2.2 with 6 results.
Calculating improvements based on keys: ['Beams'] with options: [('Beams', [])] / other keys: ['Graphwise', 'Set', 'Model', 'NED FT', 'RAG', 'LoRA', 'Naive']
No improvements calculated. Returning empty DataFrame.

In [459]:
import re

from constrerl.utils import calculate_improvements

pairs = {
    "Task 6.1": [task_6_1_1_df, task_6_1_2_df],
    "Task 6.2": [task_6_2_1_df, task_6_2_2_df],
}
for task_name, (df1, df2) in pairs.items():
    if df1.empty or df2.empty:
        print(f"Skipping {task_name} due to empty DataFrame.")
        continue
    task_name_formatted = re.sub(r"(\.| )", "_", task_name).strip().lower()
    disambiguation_changes = calculate_improvements(df1, df2)
    disambiguation_changes.style.format(
        lambda v: (
            f"+\\textcolor{{DarkGreen}}{{{v:.2f}}}"
            if v > 0
            else f"\\textcolor{{DarkRed}}{{{v:.2f}}}"
            if isinstance(v, float)
            else v
        )
    ).to_latex(
        report_dir / f"{task_name_formatted}_disambiguation.tex",
        caption=f"{mode} Set Disambiguation Changes for {task_name}",
        label=f"tab:task:{task_name_formatted}{lbl_xtra}_disambiguation",
        clines="all;data",
        hrules=True,
    )
disambiguation_changes

No base keys found in DataFrame columns: ['Graphwise', 'Set', 'Model', 'Beams', 'NED FT', 'RAG', 'LoRA', 'Naive', '$P$', '$R$', '$F_1$', '$P_{micro}$', '$R_{micro}$', '$F_{1,micro}$']. Returning original DataFrame.

TypeError: '>' not supported between instances of 'str' and 'int'